apiVersion: v1
kind: Pod
metadata:
  name: sega
  labels:
    app: sega
spec:
  containers:
    - name: tails
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
    - name: sonic
      image: nginx
      env:
        - name: NGINX_PORT
          value: "8080"