apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    app: jekyll
    run: jekyll
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      command: [ "jekyll", "new", "/site" ]
      volumeMounts:
        - mountPath: "/site"
          name: site
  containers:
    - name: jekyll
      image: kodekloud/jekyll-serve
      volumeMounts:
        - mountPath: "/site"
          name: site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
  labels:
    app: jekyll
    run: jekyll
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 30097
      name: jekyll
  selector:
    app: jekyll
    run: jekyll
---
